version: '3.8'

services:
  web:
    container_name: life-hub
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8088:80"
    environment:
      - CI_ENV=${CI_ENV}
      - CI_DB_LIFEHUB_HOSTNAME=${MYSQL_HOSTNAME}
      - CI_DB_LIFEHUB_USERNAME=${MYSQL_USER}
      - CI_DB_LIFEHUB_PASSWORD=${MYSQL_PASSWORD}
      - CI_DB_LIFEHUB_NAME=${MYSQL_DATABASE}
      - CI_ENCRYPTION_KEY=${CI_ENCRYPTION_KEY}
    depends_on:
      - db

  db:
    image: mysql:8.0  # Use MySQL 8.0 instead of 5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:21
    container_name: life_hub-node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: node server.js
    depends_on:
      - web

volumes:
  mysql_data:
