version: '3.8'

services:
  web:
    container_name: life-hub
    build:
      context: ./container-build/web/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8088:80"
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: life_hub
      MYSQL_USER: root
      MYSQL_PASSWORD: localhost
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
